apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: default
  labels:
    app: gateway-service
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
      tier: frontend
  template:
    metadata:
      labels:
        app: gateway-service
        tier: frontend
    spec:
      containers:
        - name: gateway-service
          image: gateway-service
          ports:
            - containerPort: 8080
              name: http-server
          env:
            - name: SSO-RESOURCE-SERVER_API_ADDR
              value: http://sso-resource-server/api/foos/
