eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}

server:
  port: 8080

spring:
  application:
    name: sso-authorization-server
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: bael-admin
      password: pass
    realmImportFile: baeldung-realm.json

logging:
  level:
    root: ERROR
    org:
      apache:
        http: ERROR

    springframework:
      data:
        rest:
          webmvc:
            json: ERROR
    com:
      baeldung:
        auth:
          AuthorizationServerApp: ERROR
