eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}

spring:
  application:
    name: sso-client-app-1
  security:
    oauth2:
      client:
        registration:
          ebay:
            client-id: JamesMcG-JamesMcG-PRD-42eb84eea-d7331a34
            client-secret: PRD-2eb84eea59dd-c6e5-462d-aa07-6a61
            scope: https://api.ebay.com/oauth/api_scope,https://api.ebay.com/oauth/api_scope/commerce.identity.readonly
            authorization-grant-type: authorization_code
            redirect-uri: James_McGuigan-JamesMcG-JamesM-ptzwhb
        provider:
          ebay:
            token-uri: https://api.ebay.com/identity/v1/oauth2/token
            authorization-uri: https://auth.ebay.com/oauth2/authorize
            user-info-uri: https://apiz.ebay.com/commerce/identity/v1/user
            user-name-attribute: username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8080
  servlet: 
    context-path: /

logging:
  level:
    root: DEBUG
    org:
      apache:
        http: ERROR
    springframework:
      data:
        rest:
          webmvc:
            json: ERROR
    o:
      s:
        web:
          client: DEBUG

