spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ssoClient-1
            client-secret: ssoClientSecret-1
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://sso-authorization-server/auth/realms/baeldung/protocol/openid-connect/auth
            token-uri: http://sso-authorization-server/auth/realms/baeldung/protocol/openid-connect/token
            user-info-uri: http://sso-authorization-server/auth/realms/baeldung/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8080
  servlet: 
    context-path: /

logging:
  level:
    root: ERROR
    org:
      apache:
        http: ERROR
    springframework:
      data:
        rest:
          webmvc:
            json: ERROR

