eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}

spring:
  application:
    name: sso-client-app-1
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ssoClient-1
            client-secret: ssoClientSecret-1
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: https://localhost/auth/realms/baeldung/protocol/openid-connect/auth
            token-uri: http://sso-authorization-server/auth/realms/baeldung/protocol/openid-connect/token
            user-info-uri: http://sso-authorization-server/auth/realms/baeldung/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8080
  servlet: 
    context-path: /

logging:
  level:
    root: DEBUG
    org:
      apache:
        http: DEBUG
    springframework:
      data:
        rest:
          webmvc:
            json: DEBUG

