apiVersion: v1
kind: Service
metadata:
  name: sso-resource-server
  labels:
    app: sso-resource-server
    tier: backend

spec:
  type: ClusterIP
  selector:
    app: sso-resource-server
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
