apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-service
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
      tier: frontend
  template:
    metadata:
      labels:
        app: discovery-service
        tier: frontend
    spec:
      containers:
        - name: discovery-service
          image: discovery-service
          ports:
            - containerPort: 8080
              name: http-server
          env:
            - name: SSO-RESOURCE-SERVER_API_ADDR
              value: http://sso-resource-server/api/foos/
