apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-service
    tier: frontend
spec:
  type: NodePort
#  type: LoadBalancer
  selector:
    app: discovery-service
    tier: frontend
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      name: http-server
