eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
#  instance:
#    statusPageUrlPath: ${management.contextPath}/info
#    healthCheckUrlPath: ${management.contextPath}/health

logging:
  level:
    root: DEBUG
    org:
      apache:
        http: DEBUG
    springframework:
      data:
        rest:
          webmvc:
            json: DEBUG

server:
  port: 8080
  servlet:
    context-path: /

####### resource server configuration properties
spring:
  application:
    name: sso-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://api.ebay.com/identity/v1/oauth2/token
#          jwk-set-uri: https://api.sandbox.ebay.com/identity/v1/oauth2/token
#          issuer-uri: http://sso-authorization-server/auth/realms/baeldung
#          jwk-set-uri: http://sso-authorization-server/auth/realms/baeldung/protocol/openid-connect/certs
